import uuid
from datetime import datetime
from mongoengine import (
    Document,
    EmbeddedDocument,
    StringField,
    DateTimeField,
    IntField,
    FloatField,
    BooleanField,
    ListField,
    DictField,
    EmbeddedDocumentField,
    EmbeddedDocumentListField,
    UUIDField,
)


class SetRecord(EmbeddedDocument):
    reps = IntField()
    weight = FloatField()
    notes = StringField(default="")


class ExerciseRecord(EmbeddedDocument):
    name = StringField(required=True)
    sets = EmbeddedDocumentListField(SetRecord)


class WorkoutSession(EmbeddedDocument):
    date = DateTimeField(default=datetime.utcnow)
    exercises = EmbeddedDocumentListField(ExerciseRecord)
    duration_minutes = IntField(default=0)
    notes = StringField(default="")


class ActiveSession(EmbeddedDocument):
    started_at = DateTimeField(default=datetime.utcnow)
    # Full workout plan generated by LLM; list of dicts [{name, sets, reps, weight}]
    workout_plan = ListField(DictField())
    current_exercise_index = IntField(default=0)
    current_set_index = IntField(default=0)
    completed_sets = ListField(DictField())
    # Celery task ID for the pending rest timer (so we can revoke it)
    rest_timer_task_id = StringField(default="")
    # Celery task ID for the pending debounce task
    debounce_task_id = StringField(default="")
    # Timestamp of the last message the user sent (used to guard rest timer race)
    last_user_message_at = DateTimeField()


class UserProfile(Document):
    """One document per user, keyed by phone number."""

    meta = {
        "collection": "user_profiles",
        "indexes": ["phone_number"],
    }

    id = UUIDField(primary_key=True, default=uuid.uuid4, binary=False)
    phone_number = StringField(required=True, unique=True)
    name = StringField(default="")
    created_at = DateTimeField(default=datetime.utcnow)

    # Persistent memory — learned organically over time
    goals = StringField(default="")
    equipment = StringField(default="")
    injuries = StringField(default="")
    preferences = StringField(default="")
    notes = StringField(default="")

    # Workout history (most recent sessions first for easy context building)
    sessions = EmbeddedDocumentListField(WorkoutSession)

    # Active workout state (None when not in session)
    active_session = EmbeddedDocumentField(ActiveSession)

    # Stats
    total_sessions = IntField(default=0)
    current_streak = IntField(default=0)
    prs = DictField()  # {"Bench Press": 225, "Squat": 315}

    def memory_summary(self) -> str:
        """Returns a compact text summary of user memory for LLM context."""
        parts = [f"Name: {self.name or 'unknown'}"]
        if self.goals:
            parts.append(f"Goals: {self.goals}")
        if self.equipment:
            parts.append(f"Equipment: {self.equipment}")
        if self.injuries:
            parts.append(f"Injuries/limitations: {self.injuries}")
        if self.preferences:
            parts.append(f"Preferences: {self.preferences}")
        if self.notes:
            parts.append(f"Notes: {self.notes}")
        if self.prs:
            pr_str = ", ".join(f"{k}: {v}" for k, v in self.prs.items())
            parts.append(f"PRs: {pr_str}")
        parts.append(f"Total sessions: {self.total_sessions}, Streak: {self.current_streak}")
        return "\n".join(parts)

    def recent_sessions_summary(self, n: int = 3) -> str:
        """Returns a compact summary of the last N sessions for LLM context."""
        recent = list(self.sessions)[-n:]
        if not recent:
            return "No previous sessions."
        lines = []
        for s in reversed(recent):
            date_str = s.date.strftime("%Y-%m-%d") if s.date else "unknown date"
            exercises = ", ".join(
                f"{e.name} {len(e.sets)}x{e.sets[0].reps if e.sets else '?'}"
                for e in s.exercises
            )
            lines.append(f"  {date_str}: {exercises or 'no exercises recorded'} ({s.duration_minutes}min)")
        return "\n".join(lines)
